# Site settings
title: Jekyll and Hi
email: wendi@createsalesandmarketing.com
description: > # this means to ignore newlines until "baseurl:"
  A little site dedicated to my time at MakerSquare and Learning Jekyll.
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: WendiSpeciale
github_username:  AreYouCereal

# Build settings
markdown: kramdown
