# Site settings
title: Oh My Blog 
email: wendi@createsalesandmarketing.com
description: > # this means to ignore newlines until "baseurl:"
 musings, rants and raves by wendi speciale
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: WendiSpeciale
github_username:  AreYouCereal

# Build settings
markdown: kramdown
